[phases.setup]
aptPkgs = [
  'libnss3',
  'libatk1.0-0',
  'libatk-bridge2.0-0',
  'libcups2',
  'libdrm2',
  'libxkbcommon0',
  'libxcomposite1',
  'libxdamage1',
  'libxfixes3',
  'libxrandr2',
  'libgbm1',
  'libpango-1.0-0',
  'libcairo2',
  'libasound2t64',
  'libatspi2.0-0',
  'libgtk-3-0'
]
nixPkgs = ['nodejs_18']

[phases.install]
cmds = ['npm install --omit=dev']

[start]
cmd = 'node render-server.js'
